### ISSUE TITLE
STYLE: Update Python string formatting syntax

### ISSUE THREAD

**Issue by Leengit** [InsightSoftwareConsortium/ITKSoftwareGuide#178]
Replace the likes of old-style `"My file is {file}".format(file=my_file)` with new-style `f"My file is {my_file}"`.

**Comment by dzenanz** [comment]
I forgot this is software guide repo. This needs to be done in main repo too.

**Comment by Leengit** [comment]
Submitted as [ITK Issue #3239](https://github.com/InsightSoftwareConsortium/ITK/issues/3239)

**Comment by jhlegarreta** [comment]
PR #179 did not close this since  https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/pull/179#issuecomment-1057045049 was not on the PR opening message. Closing now. Thanks for having addressed this Lee.
