### ISSUE TITLE
Update References to Gerrit to point to GitHub

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKSoftwareGuide#2]

**Comment by jhlegarreta** [comment]
PR #51 addresses this issue. All mentions to `gerrit` should be changed to `GitHub` by that PR.

**Comment by thewtex** [comment]
We will also have to update `SoftwareGuide/Latex/DevelopmentGuidelines/SoftwareProcess.tex` once `ITK` has migrated.
