### ISSUE TITLE
license of user guide and included figures

### ISSUE THREAD

**Issue by bogovicj** [InsightSoftwareConsortium/ITKSoftwareGuide#205]
@thewtex 
Is the user guide and included figures distributed under a permissive license?

I am interested in re-using (with attributes) some figures from the guide in talks and documentation, it'd be great to include a license with this repo

You know me, in particular I'm looking at [Fig 4.1 ](https://itk.org/ITKSoftwareGuide/html/Book1/ITKSoftwareGuide-Book1ch4.html#x45-54001r1) " Geometrical concepts associated with the ITK image."
Thanks for the great work  :smile:

**Comment by dzenanz** [comment]
Is [CC-3-BY](https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/blob/17227f362be0052881fc5e2f5a0657d80d9f188e/SoftwareGuide/Latex/01-PrintedPreamble-Common.tex#L41) permissive enough?
