### ISSUE TITLE
Update Ch.1-1 mailing list to discourse

### ISSUE THREAD

**Issue by addisonElliott** [InsightSoftwareConsortium/ITKSoftwareGuide#22]
In chapter 1, section 1 of the software guide, it describes how you can ask questions and get involved by interacting with the mailing list.

Update this section to link to discourse and explain that the mailing list is being replaced by discourse.

Section is found here: https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/blob/master/SoftwareGuide/Latex/Introduction/Introduction.tex#L179

**Comment by jhlegarreta** [comment]
@addisonElliott PR #45 addresses the issue.
