### ISSUE TITLE
Broken Link in Iterators

### ISSUE THREAD

**Issue by addisonElliott** [InsightSoftwareConsortium/ITKSoftwareGuide#25]
Broken link in Chapter 6 Iterators under the section *Optimizing iteration speed*

Link is to [itk::ImageBoundaryFacesCalculator](https://www.itk.org/Doxygen/html/classitk_1_1ImageBoundaryFacesCalculator.html) but it seems that it was moved to a new namespace: [itk::NeighborhoodAlgorithm::ImageBoundaryFacesCalculator](https://itk.org/Doxygen/html/structitk_1_1NeighborhoodAlgorithm_1_1ImageBoundaryFacesCalculator.html)

**Comment by jhlegarreta** [comment]
@addisonElliott Thanks for reporting issues !

A [patch](http://review.source.kitware.com/#/c/23042/) was sent to gerrit to fix the issue.

**Comment by jhlegarreta** [comment]
The gerrit topic was merged.
