### ISSUE TITLE
Create GitHub client side hooks

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKSoftwareGuide#44]
`git review-push`, etc.

**Comment by jhlegarreta** [comment]
@thewtex Can I help in this?

**Comment by thewtex** [comment]
@jhlegarreta Thanks for the offer to help.

I started to remove the Gerrit hooks, and it will work best to add the GitHub hooks at the same time. I could use your help testing the new infrastructure and documenting how to use it. A draft version should be ready next week.

**Comment by jhlegarreta** [comment]
@thewtex OK ! Ping me for testing/documentation.
