### ISSUE TITLE
Create CONTRIBUTING.md with details on how to contribute to the GitHub repository

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKSoftwareGuide#6]

**Comment by jhlegarreta** [comment]
May be some parts can be moved from the [README.md](https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/blob/master/README.md)?

And hence we could simplify that file?

Some carpentry done in  #8.

**Comment by thewtex** [comment]
Yes, we can migrate and update content from the README.

**Comment by jhlegarreta** [comment]
Nice @thewtex ! Thanks for working on this.
