### ISSUE TITLE
Update Section `3.2.7 Multi-Threading` to account for new ITK multi-threading

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITKSoftwareGuide#67]
I think there have been some important changes to ITK's multi-threading classes lately, or that there is an important effort ongoing.

The section in `\SoftwareGuide\Latex\Architecture\SystemOverview.tex` is quite short, so may be some class name or some other minor addition may be required

@dzenanz ?

**Comment by thewtex** [comment]
x-ref #85
